import { VocabularyWord, UserProgress, UserProfile } from '../types/vocabulary';

export const mockVocabulary: VocabularyWord[] = [
  // Animals Category
  {
    id: '1',
    word: 'Nocturnal',
    pronunciation: '/nɒkˈtɜːrnəl/',
    partOfSpeech: 'adjective',
    definition: 'Active during the night',
    example: 'Owls are nocturnal birds that hunt in the darkness.',
    difficulty: 'intermediate',
    category: 'Animals',
    isLearned: true,
    dateAdded: '2024-10-01',
    lastReviewed: '2024-10-05',
  },
  {
    id: '2',
    word: 'Hibernate',
    pronunciation: '/ˈhaɪbərneɪt/',
    partOfSpeech: 'verb',
    definition: 'To spend the winter in a dormant state',
    example: 'Bears hibernate during the cold winter months.',
    difficulty: 'beginner',
    category: 'Animals',
    isLearned: true,
    dateAdded: '2024-09-28',
    lastReviewed: '2024-10-06',
  },
  {
    id: '3',
    word: 'Predator',
    pronunciation: '/ˈprɛdətər/',
    partOfSpeech: 'noun',
    definition: 'An animal that hunts and kills other animals for food',
    example: 'The lion is a fierce predator in the African savanna.',
    difficulty: 'beginner',
    category: 'Animals',
    isLearned: false,
    dateAdded: '2024-10-02',
  },
  
  // Nature Category
  {
    id: '4',
    word: 'Photosynthesis',
    pronunciation: '/ˌfoʊtoʊˈsɪnθəsɪs/',
    partOfSpeech: 'noun',
    definition: 'The process by which plants make food using sunlight',
    example: 'Photosynthesis allows plants to convert sunlight into energy.',
    difficulty: 'intermediate',
    category: 'Nature',
    isLearned: false,
    dateAdded: '2024-09-30',
  },
  {
    id: '5',
    word: 'Ecosystem',
    pronunciation: '/ˈiːkoʊˌsɪstəm/',
    partOfSpeech: 'noun',
    definition: 'A community of living and non-living things in an environment',
    example: 'The rainforest ecosystem supports thousands of species.',
    difficulty: 'intermediate',
    category: 'Nature',
    isLearned: true,
    dateAdded: '2024-10-03',
    lastReviewed: '2024-10-07',
  },
  {
    id: '6',
    word: 'Erosion',
    pronunciation: '/ɪˈroʊʒən/',
    partOfSpeech: 'noun',
    definition: 'The wearing away of soil or rock by wind or water',
    example: 'Wind erosion carved the beautiful rock formations in the desert.',
    difficulty: 'beginner',
    category: 'Nature',
    isLearned: false,
    dateAdded: '2024-10-04',
  },

  // Food Category
  {
    id: '7',
    word: 'Nutritious',
    pronunciation: '/nuˈtrɪʃəs/',
    partOfSpeech: 'adjective',
    definition: 'Containing substances that help the body grow and stay healthy',
    example: 'Vegetables are nutritious and essential for a balanced diet.',
    difficulty: 'beginner',
    category: 'Food',
    isLearned: true,
    dateAdded: '2024-09-25',
    lastReviewed: '2024-10-07',
  },
  {
    id: '8',
    word: 'Savory',
    pronunciation: '/ˈseɪvəri/',
    partOfSpeech: 'adjective',
    definition: 'Having a pleasant salty or spicy flavor',
    example: 'The chef prepared a savory pasta dish with herbs and garlic.',
    difficulty: 'intermediate',
    category: 'Food',
    isLearned: false,
    dateAdded: '2024-10-05',
  },
  {
    id: '9',
    word: 'Cuisine',
    pronunciation: '/kwɪˈziːn/',
    partOfSpeech: 'noun',
    definition: 'A style of cooking from a particular country or region',
    example: 'Italian cuisine is famous for its pasta and pizza dishes.',
    difficulty: 'intermediate',
    category: 'Food',
    isLearned: false,
    dateAdded: '2024-10-06',
  },

  // Weather Category
  {
    id: '10',
    word: 'Precipitation',
    pronunciation: '/prɪˌsɪpɪˈteɪʃən/',
    partOfSpeech: 'noun',
    definition: 'Any form of water that falls from the sky',
    example: 'Rain, snow, and hail are all forms of precipitation.',
    difficulty: 'intermediate',
    category: 'Weather',
    isLearned: false,
    dateAdded: '2024-10-01',
  },
  {
    id: '11',
    word: 'Humidity',
    pronunciation: '/hjuˈmɪdəti/',
    partOfSpeech: 'noun',
    definition: 'The amount of water vapor in the air',
    example: 'High humidity makes the summer heat feel more uncomfortable.',
    difficulty: 'beginner',
    category: 'Weather',
    isLearned: true,
    dateAdded: '2024-09-29',
    lastReviewed: '2024-10-04',
  },
  {
    id: '12',
    word: 'Barometer',
    pronunciation: '/bəˈrɒmɪtər/',
    partOfSpeech: 'noun',
    definition: 'An instrument that measures air pressure',
    example: 'The barometer reading helps predict weather changes.',
    difficulty: 'advanced',
    category: 'Weather',
    isLearned: false,
    dateAdded: '2024-10-02',
  },

  // Sports Category
  {
    id: '13',
    word: 'Endurance',
    pronunciation: '/ɪnˈdʊrəns/',
    partOfSpeech: 'noun',
    definition: 'The ability to do something difficult for a long time',
    example: 'Marathon runners need great endurance to complete the race.',
    difficulty: 'intermediate',
    category: 'Sports',
    isLearned: false,
    dateAdded: '2024-10-03',
  },
  {
    id: '14',
    word: 'Agility',
    pronunciation: '/əˈdʒɪləti/',
    partOfSpeech: 'noun',
    definition: 'The ability to move quickly and easily',
    example: 'Soccer players need agility to dodge opponents and change direction.',
    difficulty: 'beginner',
    category: 'Sports',
    isLearned: true,
    dateAdded: '2024-09-27',
    lastReviewed: '2024-10-05',
  },
  {
    id: '15',
    word: 'Tournament',
    pronunciation: '/ˈtɔːrnəmənt/',
    partOfSpeech: 'noun',
    definition: 'A series of games to determine a winner',
    example: 'The tennis tournament attracted players from around the world.',
    difficulty: 'beginner',
    category: 'Sports',
    isLearned: false,
    dateAdded: '2024-10-04',
  },

  // Technology Category
  {
    id: '16',
    word: 'Algorithm',
    pronunciation: '/ˈælɡərɪðəm/',
    partOfSpeech: 'noun',
    definition: 'A set of rules or instructions for solving a problem',
    example: 'The search algorithm helps find relevant results quickly.',
    difficulty: 'advanced',
    category: 'Technology',
    isLearned: false,
    dateAdded: '2024-10-01',
  },
  {
    id: '17',
    word: 'Digital',
    pronunciation: '/ˈdɪdʒɪtəl/',
    partOfSpeech: 'adjective',
    definition: 'Using computer technology',
    example: 'Digital cameras have replaced traditional film cameras.',
    difficulty: 'beginner',
    category: 'Technology',
    isLearned: true,
    dateAdded: '2024-09-26',
    lastReviewed: '2024-10-06',
  },
  {
    id: '18',
    word: 'Interface',
    pronunciation: '/ˈɪntərfeɪs/',
    partOfSpeech: 'noun',
    definition: 'The way a user interacts with a computer or device',
    example: 'The smartphone interface is designed to be user-friendly.',
    difficulty: 'intermediate',
    category: 'Technology',
    isLearned: false,
    dateAdded: '2024-10-05',
  }
];

export const mockProgress: UserProgress = {
  totalWords: 18,
  learnedWords: 7,
  currentStreak: 5,
  longestStreak: 12,
  totalQuizzes: 15,
  correctAnswers: 42,
  weeklyGoal: 15,
  dailyProgress: [
    { date: '2024-10-01', wordsLearned: 2 },
    { date: '2024-10-02', wordsLearned: 1 },
    { date: '2024-10-03', wordsLearned: 3 },
    { date: '2024-10-04', wordsLearned: 1 },
    { date: '2024-10-05', wordsLearned: 2 },
    { date: '2024-10-06', wordsLearned: 1 },
    { date: '2024-10-07', wordsLearned: 2 }
  ]
};

export const mockProfile: UserProfile = {
  name: 'Alex Chen',
  email: 'alex.chen@email.com',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
  joinDate: '2024-09-15',
  level: 'Intermediate',
  points: 1250,
  achievements: ['First Word Learned', 'Week Streak', '100 Points', 'Quiz Master']
};